# Generated by Django 4.2.13 on 2024-07-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
    ]
